### ISSUE TITLE
Smaller image is used during landmark regression on MAFL?

### ISSUE THREAD

**Issue by ZezhouCheng** [jamt9000/DVE#7]
https://github.com/jamt9000/DVE/blob/208514419dd1eb0d27ce60876ca836d1ab8c4f4a/data_loader/data_loaders.py#L178

It seems that during unsupervised learning, the images are not cropped, while during landmark regression on MAFL (or other datasets), they are cropped by self.crop. Is that right? If yes, any reasons behind this?  

Thanks for sharing the codes! It is really useful!

**Comment by jamt9000** [comment]
They should be cropped in both cases (depending on what is in the json config).

For the unsupervised case the cropping is done inside the warping code since it needs to adjust the warp grid

https://github.com/jamt9000/DVE/blob/208514419dd1eb0d27ce60876ca836d1ab8c4f4a/data_loader/data_loaders.py#L128

https://github.com/jamt9000/DVE/blob/208514419dd1eb0d27ce60876ca836d1ab8c4f4a/utils/tps.py#L148

**Comment by ZezhouCheng** [comment]
I see, thanks!  In addition, it seems that the image width and cropping parameters are different between the hourglass network and Small net (136-2x20 vs 100 -2x15), is there any motivation behind the difference?

**Comment by jamt9000** [comment]
I think this was because the downsampling/upsampling in the hourglass required image sizes that could be divided by 2 enough times and still give an integer size, so (100-30=70) doesn't work but (136-40=96) does and is almost the same cropping ratio (70/100 = 0.7, 96/136=0.7058...).

The details for different datasets are also given in appendix D: https://arxiv.org/pdf/1908.06427.pdf

**Comment by ZezhouCheng** [comment]
Got it. Thanks!
